### PR TITLE
Regenerate C++ wrappers with Cython 0.29.21

### PR DESCRIPTION
**Pull request by enkelli**
Previous wrappers did not work on Python3.9. I'd really appreciate Python3.9 support. If I missed something, let me know. Thanks!

### CODE REVIEW

**Comment by gthomas-slack** [comment]
Thanks for doing this @enkelli Would be great if we could get this released, currently this package does not work on Python3.9

**Comment by 1ace** [comment]
@toddlipcon hi! I know you don't work at cloudera anymore, but I'm hoping you still have the rights to merge things on this project :)

**Comment by toddlipcon** [comment]
I think @attilajeges might be working on this now that I've moved on

**Comment by attilajeges** [comment]
@toddlipcon Could please add me to this project as a contributor?

**Comment by toddlipcon** [comment]
I don't have access anymore since this is under the cloudera org. I would guess Cloudera github administrator can add you.

**Comment by 1ace** [comment]
If @cloudera is not longer interested in maintaining this project (which is fair, no judgment), perhaps donating it to a collaborative like @jazzband ([FAQ](https://jazzband.co/about/faq)) is a better option?

**Pull request merged**
