### PR TITLE
up to date sasl/saslwrapper.cpp

### PR DESCRIPTION
**Pull request by Tagar**
regenerated sasl/saslwrapper.cpp with most recent Cython, with current cyrus-sasl.x86_64 :
`cyrus-sasl-devel.x86_64             2.1.26-23.el7
`

### CODE REVIEW

**Comment by Tagar** [comment]
cc @toddlipcon - please review

thank you.

**Comment by Tagar** [comment]
This PR fixes runtime linking error on EL6 platform - was getting 
```
>>>
>>> from impala.dbapi import connect
>>>
>>> connect(host='some.redacted.host', port=21055, use_ssl=True, auth_mechanism='GSSAPI')
Traceback (most recent call last):
  File "/opt/cloudera/parcels/Anaconda3/lib/python3.6/site-packages/impala/_thrift_api.py", line 194, in get_transport
    import sasl  # pylint: disable=import-error
  File "/opt/cloudera/parcels/Anaconda3/lib/python3.6/site-packages/sasl/__init__.py", line 15, in <module>
    from sasl.saslwrapper import *
ImportError: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /opt/cloudera/parcels/Anaconda3/lib/python3.6/site-packages/sasl/saslwrapper.cpython-36m-x86_64-linux-gnu.so)

```

with this PR it installs and runs fine on both EL6 and EL7

**Comment by Tagar** [comment]
cc @wesm please help review 

thanks !

**Comment by elukey** [comment]
Adding my voice to this pull request, it would be really great if this library was maintained, it is an essential working tool for the python community :)

Thanks @Tagar for the work!

**Comment by wesm** [comment]
I'm unable to maintain this, I apologize

**Comment by Tagar** [comment]
thanks for letting us know @wesm 

@elukey I've published `sasl3` package on `pypi` 
https://pypi.org/project/sasl3/
https://github.com/sparkur/python-sasl3

which is mostly master of `cloudera/python-sasl` plus this PR, plus https://github.com/cloudera/python-sasl/pull/13
and a few smaller fixes

**Pull request closed without merging**
